export default defineEventHandler(event => {
  return [
    {
      id: 126,
      slug: 'farben-des-lebens',
      ort: 'Freiburg',
      jahr: 2022,
      venue: 'c-punkt Münsterforum',
      titel: 'Farben des Lebens - Monochrome Bilder',
      untertitel: '',
      typ: 'Einzelausstellung mit Katalog',
      von: null,
      bis: null,
      kommentar: 'Farben des Lebens, monochrome Malerei, C-Punkt Münsterforum, Freiburg ',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 9,
      slug: '9',
      ort: 'Offenburg',
      jahr: 2019,
      venue: 'Dietrich-Bonhoeffer-Haus',
      titel: 'Kunst im Dietrich-Bonhoeffer-Haus',
      untertitel: 'Mit Axel Bleyer, Martin Sander, Gabi Streile, Rainer Nepita ',
      typ: 'Einzelausstellung',
      von: null,
      bis: null,
      kommentar: 'jeweils einzelne Ausstellungen in einzelnen Stockwerken ',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 7,
      slug: '2016-kunst-ort-kirche',
      ort: 'Ortenberg',
      jahr: 2016,
      venue: 'St. Bartholomäus Kirche',
      titel: 'Kunst Ort Kirche - Farbe. Aussagekraft im Bild ',
      untertitel: '',
      typ: 'Einzelausstellung',
      von: null,
      bis: null,
      kommentar: 'Kunst Ort Kirche, St. Bartholomäus Kirche, Orteberg',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 5,
      slug: '2013-rathaus',
      ort: 'Ortenberg',
      jahr: 2013,
      venue: 'Rathaus',
      titel: 'Malerei (Kunst im Rathaus)',
      untertitel: '',
      typ: 'Einzelausstellung',
      von: null,
      bis: null,
      kommentar: 'Kunst im Rathaus, Ortenberg',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 8,
      slug: 'monochrom',
      ort: 'Offenburg',
      jahr: 2013,
      venue: 'Galleries Ulrich Marx',
      titel: 'Monochrom',
      untertitel: '',
      typ: 'Einzelausstellung',
      von: null,
      bis: null,
      kommentar: 'Monochrom, Galleries Ulrich Marx, Offenburg',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 42,
      slug: '42',
      ort: 'March',
      jahr: 2008,
      venue: 'Kunstverein March',
      titel: 'Malerei / Fotografie',
      untertitel: 'Mit Géza Csizmazia',
      typ: 'Einzelausstellung',
      von: null,
      bis: null,
      kommentar: 'Malerei / Fotografie, mit Géza Csizmazia, Kunstverein, March',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 43,
      slug: '43',
      ort: 'Zunsweier',
      jahr: 2007,
      venue: 'Galerie am Berg',
      titel: 'Galerie am Berg',
      untertitel: '',
      typ: 'Einzelausstellung',
      von: null,
      bis: null,
      kommentar: 'Galerie am Berg, Zunsweier',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 44,
      slug: '44',
      ort: 'Kork',
      jahr: 2007,
      venue: 'Kunstforum',
      titel: 'Malerei und Fotografie',
      untertitel: 'mit Géza Csizmazia',
      typ: 'Einzelausstellung',
      von: null,
      bis: null,
      kommentar: 'Kunstforum Kork, mit Géza Csizmazia, Kork',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 40,
      slug: '40',
      ort: 'Renchen',
      jahr: 2006,
      venue: 'Galerie Owens',
      titel: 'Landschaften',
      untertitel: '',
      typ: 'Einzelausstellung',
      von: null,
      bis: null,
      kommentar: 'Landschaften, Galerie Owens, Renchen',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 41,
      slug: '41',
      ort: 'Haslach',
      jahr: 2006,
      venue: 'Kunstverein Mittleres Kinzigtal',
      titel: 'Natur und Architektur',
      untertitel: 'Mit Géza Csizmazia',
      typ: 'Einzelausstellung',
      von: null,
      bis: null,
      kommentar: 'Kunstverein Mittleres Kinzigtal, Mit Géza Csizmazia, Haslach',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 39,
      slug: '39',
      ort: 'Offenburg',
      jahr: 2004,
      venue: 'Galerie im Artforum, Künstlerkreis Ortenau',
      titel: 'In der Malerei unterwegs',
      untertitel: '',
      typ: 'Einzelausstellung',
      von: null,
      bis: null,
      kommentar: 'In der Malerei unterwegs, Galerie im Artforum, Künstlerkreis Ortenau, Offenburg',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 38,
      slug: '38',
      ort: 'Offenburg',
      jahr: 2002,
      venue: 'Klinikum Offenburg',
      titel: 'Paarweise',
      untertitel: 'Mit Albert Reichenbach',
      typ: 'Einzelausstellung',
      von: null,
      bis: null,
      kommentar: 'Paarweise, mit Albert Reichenbach, Offenburg',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 37,
      slug: '37',
      ort: 'Zunsweier',
      jahr: 2001,
      venue: 'Galerie am Berg',
      titel: 'Malerei \u0026 Keramikplastik',
      untertitel: 'Mit Manfred Emmenegger',
      typ: 'Einzelausstellung',
      von: null,
      bis: null,
      kommentar: 'Malerei \u0026 Keramikplastik, mit Manfred Emmenegger, Galerie am Berg, Zunsweier',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 36,
      slug: '36',
      ort: 'Offenburg',
      jahr: 1999,
      venue: 'Museum im Ritterhaus',
      titel: 'Natur',
      untertitel: 'Spiegel des Inneren',
      typ: 'Einzelausstellung',
      von: null,
      bis: null,
      kommentar: 'Natur - Spiegel des Inneren, Museum im Ritterhaus, Offenburg',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 95,
      slug: '95',
      ort: 'Offenburg',
      jahr: 1998,
      venue: 'Galerie „Alte Wäscherei“',
      titel: '„Arbeitszeit“',
      untertitel: 'Mit Csizmazia, Emmenegger, Teipelke, Schultz-Koernig',
      typ: 'Einzelausstellung',
      von: null,
      bis: null,
      kommentar: '',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 35,
      slug: '35',
      ort: 'Bruchsal',
      jahr: 1997,
      venue: 'Städtische Galerie',
      titel: 'Malerei \u0026 Zeichnung',
      untertitel: '',
      typ: 'Einzelausstellung',
      von: null,
      bis: null,
      kommentar: 'Malerei \u0026 Zeichnung, Städtische Galerie, Bruchsal',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 34,
      slug: '34',
      ort: 'Bad Krozingen',
      jahr: 1997,
      venue: 'Herzzentrum',
      titel: 'Kunst in der Klinik',
      untertitel: '',
      typ: 'Einzelausstellung',
      von: null,
      bis: null,
      kommentar: 'Kunst in der Klinik, Herzzentrum, Bad Krozingen',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 33,
      slug: '33',
      ort: 'Karlsruhe',
      jahr: 1995,
      venue: 'Galerie Akzente',
      titel: 'Malerei',
      untertitel: '',
      typ: 'Einzelausstellung',
      von: null,
      bis: null,
      kommentar: 'Malerei, Galerie Akzente, Karlsruhe',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 31,
      slug: '31',
      ort: 'Mainz',
      jahr: 1994,
      venue: 'Galerie der Stadt Mainz',
      titel: 'Brückenturm',
      untertitel: '',
      typ: 'Einzelausstellung',
      von: null,
      bis: null,
      kommentar: 'Brückenturm, Galerie der Stadt Mainz, Mainz',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 24,
      slug: '24',
      ort: 'Lahr',
      jahr: 1994,
      venue: 'Galerie Wild',
      titel: 'Malerei',
      untertitel: 'Bilder 1992 - 1994',
      typ: 'Einzelausstellung',
      von: null,
      bis: null,
      kommentar: 'Malerei - Bilder 1992 - 1994, Galerie Wild, Lahr',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 32,
      slug: '32',
      ort: 'Schramberg',
      jahr: 1994,
      venue: 'Podium Kunst',
      titel: 'Malerei',
      untertitel: '',
      typ: 'Einzelausstellung',
      von: null,
      bis: null,
      kommentar: 'Malerei, Podium Kunst, Schramberg',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 30,
      slug: '30',
      ort: 'Rohrdorf',
      jahr: 1993,
      venue: 'Galerie Györfi',
      titel: 'Malerei',
      untertitel: 'Mit Heidi Kucher und Guido Kucznierz',
      typ: 'Einzelausstellung',
      von: null,
      bis: null,
      kommentar: '',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 29,
      slug: '29',
      ort: 'Strasbourg',
      jahr: 1993,
      venue: 'Galerie du Faisan',
      titel: 'Malerei',
      untertitel: '',
      typ: 'Einzelausstellung',
      von: null,
      bis: null,
      kommentar: 'Malerei, Galerie du Faisan, Strasbourg',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 26,
      slug: '26',
      ort: 'Haslach',
      jahr: 1991,
      venue: 'Kunstverein Mittleres Kinzigtal, Kapuzinerkloster',
      titel: 'Malerei',
      untertitel: '',
      typ: 'Einzelausstellung',
      von: null,
      bis: null,
      kommentar: 'Malerei, Kunstverein Mittleres Kinzigtal, Kapuzinerkloster, Haslach',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 27,
      slug: '27',
      ort: 'Zell a. H.',
      jahr: 1991,
      venue: 'Walter-Bischoff-Galerie',
      titel: '',
      untertitel: '',
      typ: 'Einzelausstellung',
      von: null,
      bis: null,
      kommentar: 'Walter-Bischoff-Galerie, Zell a. H.',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 25,
      slug: '25',
      ort: 'Offenburg',
      jahr: 1989,
      venue: 'Staatliches Schulamt',
      titel: '',
      untertitel: '',
      typ: 'Einzelausstellung',
      von: null,
      bis: null,
      kommentar: 'Staatliches Schulamt, Offenburg',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 23,
      slug: '23',
      ort: 'Karlsruhe',
      jahr: 1989,
      venue: 'Künstlerhaus',
      titel: 'Malerei',
      untertitel: 'Mit Rainer Nepita und Werner Schmidt',
      typ: 'Einzelausstellung',
      von: null,
      bis: null,
      kommentar: 'Malerei, mit Rainer Nepita und Werner Schmidt, Künstlerhaus, Karlsruhe',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 22,
      slug: '22',
      ort: 'Freiburg',
      jahr: 1988,
      venue: 'Galerie im Schwarzen Kloster',
      titel: 'Malerei',
      untertitel: 'Mit Rainer Nepita und Werner Schmidt',
      typ: 'Einzelausstellung',
      von: null,
      bis: null,
      kommentar: 'Malerei, mit Rainer Nepita und Werner Schmidt, Schwarzes Kloster, Freiburg',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 2,
      slug: 'durchgang',
      ort: 'Offenburg',
      jahr: 1987,
      venue: 'Stadthalle / Sparkasse',
      titel: 'Durchgang',
      untertitel: 'Mit R. Braxmaier, H. Heider, W. Schmidt \u0026 G. Streile ',
      typ: 'Einzelausstellung',
      von: null,
      bis: null,
      kommentar:
        '1986 war die neue Garage neben der Sparkasse in Offenburg fertig. Zwischen ihr und der Stadthalle war ein Durchgang mit eingeplant worden. \r\n In diesem Durchgang haben sich große Flächen zur Ausgestaltung angeboten. Die Stadt Offenburg unter dem damaligen Oberbürgermeister Martin Grüber hat unserem damals neugegründeten Künstlerkreis (Galerie „Alte Wäscherei“, 1985 eröffnet) den Auftrag gegeben, diesen Durchgang künstlerisch zu gestalten. \r\n Nach der Fertigstellung dieser künstlerischen Arbeit wurde im Januar 1987 im Foyer der Stadthalle eine Ausstellung der beteiligten fünf Künstler/innen eröffnet.',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 21,
      slug: '21',
      ort: 'Offenburg',
      jahr: 1987,
      venue: 'Werkstattgalerie "Alte Wäscherei"',
      titel: 'Bilder von 1985 - 1987',
      untertitel: '',
      typ: 'Einzelausstellung',
      von: null,
      bis: null,
      kommentar: 'Bilder von 1985 - 1987, Werkstattgalerie "Alte Wäscherei", Offenburg',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 20,
      slug: '20',
      ort: 'Amriswil / Schweiz',
      jahr: 1986,
      venue: 'Schloss Hagenwil',
      titel: 'Malerei auf Papier',
      untertitel: '',
      typ: 'Einzelausstellung',
      von: null,
      bis: null,
      kommentar: 'Malerei auf Papier, Schloss Hagenwil, Amriswil, Schweiz',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 19,
      slug: '19',
      ort: 'Meersburg',
      jahr: 1985,
      venue: 'Barockschloss',
      titel: '„Figurenbilder, Landschaften, Stilleben“',
      untertitel: 'Städtische Galerie im Barockschloss',
      typ: 'Einzelausstellung',
      von: null,
      bis: null,
      kommentar: '',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 1,
      slug: '1',
      ort: 'Offenburg',
      jahr: 1981,
      venue: 'Städtisches Verkehrsamt',
      titel: 'Gemälde, Zeichnungen, Radierungen, Aquarelle',
      untertitel: '',
      typ: 'Einzelausstellung',
      von: null,
      bis: null,
      kommentar: '',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
  ]
})
