export default defineEventHandler(event => {
  return [
    {
      id: 6,
      slug: '6',
      ort: 'Schramberg',
      jahr: 2018,
      venue: 'Galerie Podium Kunst im Schloß',
      titel: '40 Jahre Podium Kunst ',
      untertitel: 'Jubiläumsausstellung 2018',
      typ: 'Ausstellungsbeteiligung',
      von: null,
      bis: null,
      kommentar: '',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 13,
      slug: '13',
      ort: 'Durbach',
      jahr: 2017,
      venue: 'Museum Hurrle',
      titel: 'Auf unbekanntem Terrain.',
      untertitel: 'Landschaft in der Kunst nach 1945',
      typ: 'Ausstellungsbeteiligung',
      von: null,
      bis: null,
      kommentar:
        'Europe | Exhibitions | news | artports | September 23, 2017 |\r\nFortschritt und Zeitgeist formen und verändern seit Jahrhunderten unsere Umwelt. Spätestens seit der industriellen Revolution des 19. Jahrhunderts vollzieht sich dieser Wandel in reißender Geschwindigkeit. Mit der Expansion des Städtischen haben sich neue Qualitäten und Perspektiven entwickelt, durch die sich Landschaft heute weit über das vordergründig Ländliche hinaus in weite Lebensbereiche erstreckt.\u2028Mit der Zäsur des 2. Weltkrieges erschien das gegenständliche Abbild in der Kunst als nicht mehr zeitgemäß, und für annähernd zwei Jahrzehnte avancierte die Abstraktion zur dominierenden Weltsprache in der Kunst. Trotz dieses radikalen Bruches blieb das Motiv der Landschaft eine wichtige Referenz und wird in einer Vielzahl ungegenständlicher Werke reflektiert.\u2028Zu dieser Zeit trat zur geografisch definierten Landschaft ein neuer, sozial und kulturell konstruierter Landschaftsbegriff hinzu. Er orientiert sich weniger an einer physisch realen Situation, sondern es handelt sich vielmehr um eine Interpretation der wahrgenommenen Welt, die durch Prägung und Erfahrung bestimmt ist. Durch ihn konnte die Landschaft in den Nachkriegsjahren in Bereiche des Ungegenständlichen vordringen, bevor sie zu Beginn der sechziger Jahre als erkennbares Motiv in die Kunst zurückkehren sollte.\r\n\r\nIn vier Kapiteln und mit über 100 Wlerken verschiedenster Künstler spürt die von dem Berliner Kunsthistoriker Ronald Puff kuratierte Ausstellung der Reflexion von Landschaft in der Kunst seit 1945 nach und lässt Schritt für Schritt sichtbar werden, wie sie sich vom mimetischen Abbild hin zu einer Vorstellung entwickelte, die sich jenseits des Abbildes manifestiert.\r\n\r\nDen Auftakt zur Ausstellung bildet das Kapitel Dokument, das sich der Objektivität und den Facetten des Realismus in der Landschaftsdarstellung zuwendet. Dabei reicht das Panorama über fotografische Arbeiten von Michael Wesely und Ottmar Hörl bis zum brillanten Hyperrealismus von Bernd Schwering und Andreas Orosz.\u2028Die unter der Überschrift Expression versammelten Positionen zeichnen ein Landschaftsbild, in dem das Motiv zum Spiegel eines weitreichenden Diskurses wird. Beispielsweise wird die politische Lage der BRD oder die Situation des geteilten Berlin ebenso reflektiert wie das gesellschaftliche und kulturelle Umfeld innerhalb der DDR. Hiervon entwerfen die kraftvollen Werke von unter anderem Georg Baselitz, K.H. Hödicke, Wolfgang Mattheuer oder Hans Scheib ein aufschlussreiches Bild.\u2028Schließlich widmet sich das Kapitel Poesie, das als letzte Station dem augenfälligen Abbild von Landschaft verpflichtet ist, den nichtsprachlichen, poetischen Qualitäten.\u2028In den berührenden Werken von Gerhard Altenbourg, Horst Janssen und Richard Oelze eröffnen sich Landschaften, die zwischen Gegenständlichkeit und Abstraktion oszillieren und deren Ausdruckskraft sich dem rational Fass- und Beschreibbaren entziehen.\u2028Diese Werke bilden die Brücke zum Abschluss der Ausstellung mit dem Titel Jenseits des Abbildes, in dem herausragende Werke der Nachkriegsmoderne, von Willi Baumeister über Bernard Schulze und Gotthard Graubner bis zu bedeutenden Positionen der Gegenwart wie Pia Fries, Per Kirkeby, Olav Christopher Jenssen, Hanspeter Münch und Eugene Leroy zeigen, dass Landschaft auch in der Ungegenständlichkeit ein wichtiges und reflektiertes Thema darstellt, das über sich selbst hinausweist.\r\n\r\nPR: Sammlung Hurrle, Durbach\r\nAusstellung vom 16. September 2017 bis 4. Februar 2018\r\n77770\u2028Museum für aktuelle Kunst\u2028Sammlung Hurrle Durbach\u2028Vier Jahreszeiten Durbach GmbH \u0026 Co. KGAlmstraße 49\u2028D-77770 Durbach',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 14,
      slug: '14',
      ort: 'Rastatt',
      jahr: 2015,
      venue: 'Städt. Galerie Fruchthalle',
      titel: 'Sammlung Westermann',
      untertitel: '',
      typ: 'Ausstellungsbeteiligung',
      von: null,
      bis: null,
      kommentar: '',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 128,
      slug: '128',
      ort: '',
      jahr: 2014,
      venue: '',
      titel: '30 Jahre',
      untertitel: 'Kunstverein Mittleres Kinzigtal',
      typ: 'Ausstellungsbeteiligung mit Katalog',
      von: null,
      bis: null,
      kommentar: '',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 10,
      slug: '10',
      ort: 'Schramberg???',
      jahr: 2012,
      venue: 'Landesgartenschau',
      titel: 'Natur und Landschaft heute',
      untertitel: 'Malerei aus dem Südwesten',
      typ: 'Ausstellungsbeteiligung',
      von: null,
      bis: null,
      kommentar: '',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 17,
      slug: '17',
      ort: 'Nagold',
      jahr: 2012,
      venue: 'Teufel-Areal, Landesgartenschau',
      titel: 'Natur und Landschaft heute',
      untertitel: 'Malerei aus dem Südwesten',
      typ: 'Ausstellungsbeteiligung',
      von: null,
      bis: null,
      kommentar: '',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 125,
      slug: '125',
      ort: 'Offenburg',
      jahr: 2011,
      venue: 'Galerie im Artforum',
      titel: '"Landschaft"',
      untertitel: '',
      typ: 'Ausstellungsbeteiligung',
      von: null,
      bis: null,
      kommentar: '',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 12,
      slug: '12',
      ort: 'Offenburg',
      jahr: 2010,
      venue: 'Städtische Galerie',
      titel: 'Aus dem Fundus',
      untertitel: 'Die Offenburger Kunstsammlung stellt sich vor',
      typ: 'Ausstellungsbeteiligung',
      von: null,
      bis: null,
      kommentar: '',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 11,
      slug: '11',
      ort: 'Ettenheimmünster',
      jahr: 2010,
      venue: 'Galerie Linda Treiber',
      titel: 'Kunstschaffende aus der Ortenau',
      untertitel: '',
      typ: 'Ausstellungsbeteiligung',
      von: null,
      bis: null,
      kommentar: '',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 16,
      slug: '16',
      ort: 'Rastatt',
      jahr: 2009,
      venue: 'Historisches Rathaus',
      titel: 'Revolution in der Box',
      untertitel: 'Tag der Badischen Revolution (Sammlung Westermann)',
      typ: 'Ausstellungsbeteiligung',
      von: null,
      bis: null,
      kommentar: '',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 15,
      slug: '15',
      ort: 'Haslach',
      jahr: 2009,
      venue: 'Kunstverein Mittleres Kinzigtal, Kapuzinerkloster',
      titel: 'Schwarzwaldbild 4',
      untertitel: '',
      typ: 'Ausstellungsbeteiligung',
      von: null,
      bis: null,
      kommentar: '',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 124,
      slug: '124',
      ort: 'Baden-Baden',
      jahr: 2009,
      venue: 'Altes Dampfbad',
      titel: '"Vasen"',
      untertitel: '',
      typ: 'Ausstellungsbeteiligung',
      von: null,
      bis: null,
      kommentar: '',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 127,
      slug: '127',
      ort: 'Offenburg',
      jahr: 2008,
      venue: 'Galerie im Artforum',
      titel: 'Geteilt',
      untertitel: 'Künsterkreis Ortenau',
      typ: 'Ausstellungsbeteiligung',
      von: null,
      bis: null,
      kommentar: '',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 123,
      slug: '123',
      ort: 'Lauterbach',
      jahr: 2007,
      venue: 'Galerie Kimmich',
      titel: 'Landschaft im 21. Jahrhundert',
      untertitel: '',
      typ: 'Ausstellungsbeteiligung',
      von: null,
      bis: null,
      kommentar: '',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 122,
      slug: '122',
      ort: 'Olsztyn, Polen',
      jahr: 2007,
      venue: 'Galeria Sztuki ',
      titel: '"Most sztuki - Kunst-Brücke"',
      untertitel: '',
      typ: 'Ausstellungsbeteiligung mit Katalog',
      von: null,
      bis: null,
      kommentar: '',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 119,
      slug: '119',
      ort: 'Freiburg',
      jahr: 2006,
      venue: 'E-Werk',
      titel: 'Künstlerkreis Ortenau',
      untertitel: '',
      typ: 'Ausstellungsbeteiligung',
      von: null,
      bis: null,
      kommentar: '',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 120,
      slug: '120',
      ort: 'Fürstenwalde',
      jahr: 2006,
      venue: 'Galerie Altes Rathaus',
      titel: '7. Miniatur in der bildenden Kunst',
      untertitel: '',
      typ: 'Ausstellungsbeteiligung mit Katalog',
      von: null,
      bis: null,
      kommentar: '',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 121,
      slug: '121',
      ort: 'Zell a.H.',
      jahr: 2006,
      venue: 'Villa Haiss Museum',
      titel: '„40 Künstler der Ortenau“',
      untertitel: '',
      typ: 'Ausstellungsbeteiligung',
      von: null,
      bis: null,
      kommentar: '',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 118,
      slug: '118',
      ort: 'Offenburg',
      jahr: 2005,
      venue: 'Galerie im Gewölbe',
      titel: '„Formart“',
      untertitel: '',
      typ: 'Ausstellungsbeteiligung',
      von: null,
      bis: null,
      kommentar: '',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 117,
      slug: '117',
      ort: 'Ettlingen',
      jahr: 2004,
      venue: 'Museum Schloß Ettlingen',
      titel: '„Landschaft – Zeitgenössische Positionen“',
      untertitel: '',
      typ: 'Ausstellungsbeteiligung mit Katalog',
      von: null,
      bis: null,
      kommentar: '',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 116,
      slug: '116',
      ort: 'Schramberg',
      jahr: 2002,
      venue: 'Galerie Podium Kunst im Schloß',
      titel: '„Vergangenheit“',
      untertitel: '',
      typ: 'Ausstellungsbeteiligung mit Katalog',
      von: null,
      bis: null,
      kommentar: '',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 114,
      slug: '114',
      ort: 'Strasbourg',
      jahr: 2002,
      venue: "Zone d' art",
      titel: '„Duell?“',
      untertitel: 'Accrochage Franco-Allemand',
      typ: 'Ausstellungsbeteiligung',
      von: null,
      bis: null,
      kommentar: '',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 113,
      slug: '113',
      ort: 'Offenburg',
      jahr: 2002,
      venue: 'Galerie im Artforum',
      titel: '„Haute Couture“',
      untertitel: '',
      typ: 'Ausstellungsbeteiligung',
      von: null,
      bis: null,
      kommentar: '',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 115,
      slug: '115',
      ort: 'Berlin',
      jahr: 2002,
      venue: 'Landesvertretung Baden-Württemberg',
      titel: 'Installation des Künstlerkreises Ortenau',
      untertitel: '',
      typ: 'Ausstellungsbeteiligung',
      von: null,
      bis: null,
      kommentar: '',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 112,
      slug: '112',
      ort: 'Lahr',
      jahr: 2001,
      venue: 'Galerie Wild',
      titel: '„Neue Ernte“',
      untertitel: '',
      typ: 'Ausstellungsbeteiligung',
      von: null,
      bis: null,
      kommentar: '',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 110,
      slug: '110',
      ort: 'Baden-Baden',
      jahr: 2001,
      venue: 'Staatliche Kunsthalle',
      titel: '„Was mir gefällt“',
      untertitel: 'Gesellschaft der Freunde junger Kunst',
      typ: 'Ausstellungsbeteiligung',
      von: null,
      bis: null,
      kommentar: '',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 108,
      slug: '108',
      ort: 'Freiburg',
      jahr: 2001,
      venue: 'Städtische Galerie Schwarzes Kloster',
      titel: '„Zeichnung“',
      untertitel: '',
      typ: 'Ausstellungsbeteiligung',
      von: null,
      bis: null,
      kommentar: '',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 111,
      slug: '111',
      ort: 'Renchen',
      jahr: 2001,
      venue: 'Galerie Owens',
      titel: '„Künstlerkreis Ortenau“',
      untertitel: '',
      typ: 'Ausstellungsbeteiligung',
      von: null,
      bis: null,
      kommentar: '',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 109,
      slug: '109',
      ort: 'Haslach',
      jahr: 2001,
      venue: 'Kunstverein Mittleres Kinzigtal, Kapuzinerkloster',
      titel: 'Schwarzwaldbild 2',
      untertitel: '',
      typ: 'Ausstellungsbeteiligung',
      von: null,
      bis: null,
      kommentar: '',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 106,
      slug: '106',
      ort: 'Offenburg',
      jahr: 2000,
      venue: 'Galerie Artforum',
      titel: '„Reisen“',
      untertitel: 'Künstlerkreis Ortenau',
      typ: 'Ausstellungsbeteiligung',
      von: null,
      bis: null,
      kommentar: '',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 104,
      slug: '104',
      ort: 'Tettnang',
      jahr: 2000,
      venue: 'Galerie im Torschloß',
      titel: '„Malerische Malerei“',
      untertitel: '',
      typ: 'Ausstellungsbeteiligung',
      von: null,
      bis: null,
      kommentar: '',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 107,
      slug: '107',
      ort: 'Schramberg',
      jahr: 2000,
      venue: 'Galerie Podium Kunst im Schloss',
      titel: '„Tanne und Baum“',
      untertitel: '',
      typ: 'Ausstellungsbeteiligung',
      von: null,
      bis: null,
      kommentar: '',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 105,
      slug: '105',
      ort: 'Baden-Baden',
      jahr: 2000,
      venue: 'Kunsthalle',
      titel: '„Compakt 2000“',
      untertitel: 'Gesellschaft der Freunde junger Kunst',
      typ: 'Ausstellungsbeteiligung',
      von: null,
      bis: null,
      kommentar: '',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 98,
      slug: '98',
      ort: 'Strasbourg',
      jahr: 1999,
      venue: 'Messe',
      titel: "„st'art 99“",
      untertitel: 'Vertreten durch Galerie Wild',
      typ: 'Ausstellungsbeteiligung',
      von: null,
      bis: null,
      kommentar: '',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 101,
      slug: '101',
      ort: 'Bonn',
      jahr: 1999,
      venue: 'Vertretung des Landes Baden-Württemberg',
      titel: '„Unterwegs“',
      untertitel: 'Landesverband BBK Baden-Württemberg',
      typ: 'Ausstellungsbeteiligung',
      von: null,
      bis: null,
      kommentar: '',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 99,
      slug: '99',
      ort: 'Lahr',
      jahr: 1999,
      venue: 'Städtische Galerie im Alten Rathaus',
      titel: '„Kunst aus Wellpappe“',
      untertitel: '',
      typ: 'Ausstellungsbeteiligung mit Katalog',
      von: null,
      bis: null,
      kommentar: '',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 102,
      slug: '102',
      ort: 'St. Andreasberg',
      jahr: 1999,
      venue: 'Galerie Rathaus-Scheune',
      titel: '„Natur und Mensch“',
      untertitel: '',
      typ: 'Ausstellungsbeteiligung mit Katalog',
      von: null,
      bis: null,
      kommentar: '',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 100,
      slug: '100',
      ort: 'Rastatt',
      jahr: 1999,
      venue: 'Städtische Galerie Fruchthalle',
      titel: '„Revolution in der Box“',
      untertitel: 'Die Badische Revolution 1848/49 in der Sammlung Westermann',
      typ: 'Ausstellungsbeteiligung mit Katalog',
      von: null,
      bis: null,
      kommentar: '',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 103,
      slug: '103',
      ort: 'Offenburg',
      jahr: 1999,
      venue: 'Oberrheinmesse',
      titel: 'Ortenauer Kunstforum',
      untertitel: '',
      typ: 'Ausstellungsbeteiligung',
      von: null,
      bis: null,
      kommentar: '',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 93,
      slug: '93',
      ort: 'Baden-Baden',
      jahr: 1998,
      venue: 'Galerie der Gesellschaft der Freunde junger Kunst',
      titel: '„Druck“',
      untertitel: 'Gesellschaft der Freunde junger Kunst',
      typ: 'Ausstellungsbeteiligung',
      von: null,
      bis: null,
      kommentar: '',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 97,
      slug: '97',
      ort: 'Halberstadt \u0026 Weißenfels',
      jahr: 1998,
      venue: 'Museum im Gleimhaus \u0026Schloßmuseum',
      titel: '„Neues zu G.A. Bürger“',
      untertitel: '',
      typ: 'Ausstellungsbeteiligung',
      von: null,
      bis: null,
      kommentar: '',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 91,
      slug: '91',
      ort: 'Strasbourg',
      jahr: 1998,
      venue: "Clinique de l' Orangerie",
      titel: '„Paysages“',
      untertitel: '',
      typ: 'Ausstellungsbeteiligung',
      von: null,
      bis: null,
      kommentar: '',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 96,
      slug: '96',
      ort: 'Offenburg',
      jahr: 1998,
      venue: 'Galerie im Klinikum',
      titel: '????',
      untertitel: '',
      typ: 'Ausstellungsbeteiligung',
      von: null,
      bis: null,
      kommentar: '',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 94,
      slug: '94',
      ort: 'Offenburg',
      jahr: 1998,
      venue: 'Landratsamt',
      titel: 'Kunstsammlung des Ortenaukreises',
      untertitel: '',
      typ: 'Ausstellungsbeteiligung',
      von: null,
      bis: null,
      kommentar: '',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 90,
      slug: '90',
      ort: 'Strasbourg',
      jahr: 1998,
      venue: 'Kunstmesse',
      titel: "„st' art 98“",
      untertitel: 'Vertreten durch Galerie Wild',
      typ: 'Ausstellungsbeteiligung',
      von: null,
      bis: null,
      kommentar: '',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 92,
      slug: '92',
      ort: 'Colmar',
      jahr: 1998,
      venue: 'Parc des Expositions de Colmar',
      titel: '„Les Toques Modèles“',
      untertitel: '',
      typ: 'Ausstellungsbeteiligung',
      von: null,
      bis: null,
      kommentar: '',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 85,
      slug: '85',
      ort: 'Haslach',
      jahr: 1997,
      venue: 'Kunstverein Mittleres Kinzigtal, Kapuzinerkloster',
      titel: '„Schwarzwaldbild“',
      untertitel: '',
      typ: 'Ausstellungsbeteiligung',
      von: null,
      bis: null,
      kommentar: '',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 86,
      slug: '86',
      ort: 'Höchstadt an der Aisch',
      jahr: 1997,
      venue: 'Kunstverein',
      titel: '„Kunst im Schloß“',
      untertitel: '',
      typ: 'Ausstellungsbeteiligung',
      von: null,
      bis: null,
      kommentar: '',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 89,
      slug: '89',
      ort: 'Freiburg',
      jahr: 1997,
      venue: 'Städtische Galerie im Schwarzen Kloster',
      titel: '„Der Kunstsalon“',
      untertitel: 'BBK Südbaden',
      typ: 'Ausstellungsbeteiligung',
      von: null,
      bis: null,
      kommentar: '',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 88,
      slug: '88',
      ort: 'Lahr',
      jahr: 1997,
      venue: 'Galerie Wild',
      titel: '„Kunst Herbst – Herbst Kunst“',
      untertitel: '',
      typ: 'Ausstellungsbeteiligung',
      von: null,
      bis: null,
      kommentar: '',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 87,
      slug: '87',
      ort: 'Achberg',
      jahr: 1997,
      venue: 'Schloß Achberg',
      titel: '„Trotz und Übermut“',
      untertitel: 'Sammlung Horn',
      typ: 'Ausstellungsbeteiligung mit Katalog',
      von: null,
      bis: null,
      kommentar: '',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 82,
      slug: '82',
      ort: 'Strasbourg',
      jahr: 1996,
      venue: 'Kunstmesse',
      titel: "„st' art 96“",
      untertitel: 'Vertreten durch Galerie Wild',
      typ: 'Ausstellungsbeteiligung',
      von: null,
      bis: null,
      kommentar: '',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 79,
      slug: '79',
      ort: 'Freiburg',
      jahr: 1995,
      venue: 'Städtische Galerie im Schwarzen Kloster',
      titel: 'Schwarzwald jetzt und hier',
      untertitel: '',
      typ: 'Ausstellungsbeteiligung',
      von: null,
      bis: null,
      kommentar: '',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 81,
      slug: '81',
      ort: 'Offenburg',
      jahr: 1995,
      venue: 'Galerie Alte Wäscherei',
      titel: 'Zeitgenössische Kunst im sakralen Raum - Ein Dialog',
      untertitel: 'Künstlerkreis Ortenau',
      typ: 'Ausstellungsbeteiligung mit Katalog',
      von: null,
      bis: null,
      kommentar: '',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 80,
      slug: '80',
      ort: 'Strasbourg',
      jahr: 1995,
      venue: 'Galerie Faisant',
      titel: 'Hommage à Marcel Cahn',
      untertitel: '',
      typ: 'Ausstellungsbeteiligung',
      von: null,
      bis: null,
      kommentar: '',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 77,
      slug: '77',
      ort: 'Offenburg',
      jahr: 1994,
      venue: 'Städtische Galerie im Spitalspeicher',
      titel: 'Zeitgenössische Kunst in der Ortenau',
      untertitel: '',
      typ: 'Ausstellungsbeteiligung',
      von: null,
      bis: null,
      kommentar: '',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 76,
      slug: '76',
      ort: 'Offenburg',
      jahr: 1994,
      venue: 'Fachhochschule',
      titel: 'Mensch und Technik',
      untertitel: '',
      typ: 'Ausstellungsbeteiligung mit Katalog',
      von: null,
      bis: null,
      kommentar: '',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 75,
      slug: '75',
      ort: 'Augsburg',
      jahr: 1994,
      venue: 'Rathaus',
      titel: 'Menschen und Rechte.',
      untertitel: 'Hommage à Heinrich Heine',
      typ: 'Ausstellungsbeteiligung mit Katalog',
      von: null,
      bis: null,
      kommentar: '',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 78,
      slug: '78',
      ort: 'Böblingen',
      jahr: 1994,
      venue: 'Galerie contact',
      titel: 'verpackt, verschnürt, verschickt',
      untertitel: '',
      typ: 'Ausstellungsbeteiligung mit Katalog',
      von: null,
      bis: null,
      kommentar: '',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 74,
      slug: '74',
      ort: 'Karlsruhe',
      jahr: 1992,
      venue: 'Kongresszentrum',
      titel: 'Und sie bewegt sich doch',
      untertitel: 'Bundesverband Bildender Künstler',
      typ: 'Ausstellungsbeteiligung mit Katalog',
      von: null,
      bis: null,
      kommentar: '',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 71,
      slug: '71',
      ort: 'Kronach',
      jahr: 1992,
      venue: 'Städtische Galerie',
      titel: 'Lucas-Cranach-Preis „Menschenbilder“',
      untertitel: '',
      typ: 'Ausstellungsbeteiligung mit Katalog',
      von: null,
      bis: null,
      kommentar: '',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 70,
      slug: '70',
      ort: 'St. Petersburg \u0026 Petrosawodsk \u0026 Simferopol',
      jahr: 1992,
      venue: 'Haus der Freundschaft',
      titel: 'Künstler aus Baden-Württemberg',
      untertitel: '',
      typ: 'Ausstellungsbeteiligung',
      von: null,
      bis: null,
      kommentar: '',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 72,
      slug: '72',
      ort: 'Freiburg',
      jahr: 1992,
      venue: 'IHK',
      titel: 'Bilder aus Südbaden',
      untertitel: ' Kunstsammlung IHK',
      typ: 'Ausstellungsbeteiligung mit Katalog',
      von: null,
      bis: null,
      kommentar: '',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 73,
      slug: '73',
      ort: 'Offenburg',
      jahr: 1992,
      venue: 'Galerie Alte Wäscherei',
      titel: 'Die Farbe Grau',
      untertitel: 'Künstlerkreis Ortenau',
      typ: 'Ausstellungsbeteiligung',
      von: null,
      bis: null,
      kommentar: '',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 67,
      slug: '67',
      ort: 'Wiesbaden',
      jahr: 1991,
      venue: ' Kunsthaus',
      titel: '10 x 10 x 10',
      untertitel: 'quadratisch - eckig - Kunst',
      typ: 'Ausstellungsbeteiligung mit Katalog',
      von: null,
      bis: null,
      kommentar: '',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 66,
      slug: '66',
      ort: 'Kehl',
      jahr: 1991,
      venue: 'Badische Stahlwerke',
      titel: 'Kunst aus Baden und dem Elsaß',
      untertitel: '',
      typ: 'Ausstellungsbeteiligung mit Katalog',
      von: null,
      bis: null,
      kommentar: '',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 69,
      slug: '69',
      ort: 'Offenburg',
      jahr: 1991,
      venue: 'Städtische Galerie im Spitalspeicher',
      titel: 'Kunst der Region',
      untertitel: '',
      typ: 'Ausstellungsbeteiligung',
      von: null,
      bis: null,
      kommentar: '',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 68,
      slug: '68',
      ort: 'Baden-Baden',
      jahr: 1991,
      venue: ' Gesellschaft der Freunde junger Kunst',
      titel: 'Landschaft – faxen',
      untertitel: '',
      typ: 'Ausstellungsbeteiligung',
      von: null,
      bis: null,
      kommentar: '',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 63,
      slug: '63',
      ort: 'Oberwil/Basel',
      jahr: 1990,
      venue: '',
      titel: 'Basellandschaftliche Kunstausstellung',
      untertitel: '',
      typ: 'Ausstellungsbeteiligung',
      von: null,
      bis: null,
      kommentar: '',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 65,
      slug: '65',
      ort: 'Baden-Baden',
      jahr: 1990,
      venue: 'Galerie der Gesellschaft der Freunde junger Kunst',
      titel: 'Blättern',
      untertitel: 'Gesellschaft der Freunde junger Kunst',
      typ: 'Ausstellungsbeteiligung',
      von: null,
      bis: null,
      kommentar: '',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 62,
      slug: '62',
      ort: "Civitella d'Agliano, Italien",
      jahr: 1990,
      venue: 'Castello',
      titel: 'Natura',
      untertitel: '',
      typ: 'Ausstellungsbeteiligung mit Katalog',
      von: null,
      bis: null,
      kommentar: '',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 60,
      slug: '60',
      ort: 'Mülheim \u0026 Gelsenkirchen',
      jahr: 1990,
      venue: 'Städtische Museen',
      titel: 'Der aufrechte Gang',
      untertitel: '',
      typ: 'Ausstellungsbeteiligung mit Katalog',
      von: null,
      bis: null,
      kommentar: 'Termine: 4.-17.9.1989 Unna Ausstellungshalle Kurpark ...',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 64,
      slug: '64',
      ort: 'Offenburg',
      jahr: 1990,
      venue: 'Galerie Alte Wäscherei',
      titel: 'Pas de deux',
      untertitel: 'Künstlerkreis Ortenau',
      typ: 'Ausstellungsbeteiligung',
      von: null,
      bis: null,
      kommentar: '',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 61,
      slug: '61',
      ort: 'Strasbourg',
      jahr: 1990,
      venue: 'Ancienne Laiterie',
      titel: 'Autoportraits – Repères',
      untertitel:
        'avec Jean-Louis CHARVOT, Louis DANICHER, Jean-Francois HEINTZ, Erling JOHANSSON, Iris KRAMER, Christophe MEYER, MORZUCH, Suzanne OBRECHT, Bernard QUESNIAUX, Hubert RIEBER, Marie SESTER, Jo SIMON, Agnès THUIN',
      typ: 'Ausstellungsbeteiligung mit Katalog',
      von: null,
      bis: null,
      kommentar: 'Im Rahmen einer Veranstaltungsreihe zum 100. Todestag von Vincent van Gogh',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 59,
      slug: '59',
      ort: 'Offenburg',
      jahr: 1989,
      venue: 'Galerie Alte Wäscherei',
      titel: 'Figur',
      untertitel: 'Künstlerkreis Ortenau',
      typ: 'Ausstellungsbeteiligung',
      von: null,
      bis: null,
      kommentar: '',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 58,
      slug: '58',
      ort: 'Tuttlingen',
      jahr: 1989,
      venue: 'Städtische Galerie',
      titel: 'BBK Südbaden',
      untertitel: '',
      typ: 'Ausstellungsbeteiligung',
      von: null,
      bis: null,
      kommentar: '',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 57,
      slug: '57',
      ort: 'Karlsruhe',
      jahr: 1989,
      venue: 'Landesgewerbeamt Baden-Württemberg',
      titel: 'World Games',
      untertitel: '',
      typ: 'Ausstellungsbeteiligung',
      von: null,
      bis: null,
      kommentar: '',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 56,
      slug: '56',
      ort: 'Karslruhe',
      jahr: 1989,
      venue: 'Tempel',
      titel: '1789-1989',
      untertitel: '200 Jahre Französische Revolution',
      typ: 'Ausstellungsbeteiligung mit Katalog',
      von: null,
      bis: null,
      kommentar: '',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 55,
      slug: '55',
      ort: 'Haslach i.K.',
      jahr: 1989,
      venue: 'Kapuzinerkloster',
      titel: 'Drei Länder - Malerei',
      untertitel: '',
      typ: 'Ausstellungsbeteiligung',
      von: null,
      bis: null,
      kommentar: '',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 53,
      slug: '53',
      ort: 'Freiburg i. Brsg.',
      jahr: 1988,
      venue: 'Schwarzes Kloster',
      titel: 'Malerei ???',
      untertitel: '',
      typ: 'Ausstellungsbeteiligung',
      von: null,
      bis: null,
      kommentar: '',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 52,
      slug: '52',
      ort: 'Frankfurt am Main',
      jahr: 1988,
      venue: 'Volksbank',
      titel: 'Der Fuchs',
      untertitel: '',
      typ: 'Ausstellungsbeteiligung mit Katalog',
      von: null,
      bis: null,
      kommentar: '',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 54,
      slug: '54',
      ort: 'Offenburg \u0026 Lons-le-Saunier',
      jahr: 1988,
      venue: 'Galerie „Alte Wäscherei“',
      titel: 'Stadt – Landschaft',
      untertitel: '',
      typ: 'Ausstellungsbeteiligung mit Katalog',
      von: null,
      bis: null,
      kommentar: '',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 51,
      slug: '51',
      ort: 'Rimsingen',
      jahr: 1988,
      venue: 'Galerie Schloß Rimsingen',
      titel: 'Landschaft',
      untertitel: '',
      typ: 'Ausstellungsbeteiligung',
      von: null,
      bis: null,
      kommentar: '',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 129,
      slug: '1987-bausparkasse',
      ort: '???',
      jahr: 1987,
      venue: '???',
      titel: 'Ausstellung Bausparkasse',
      untertitel: '',
      typ: 'Ausstellungsbeteiligung mit Katalog',
      von: null,
      bis: null,
      kommentar: '',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 48,
      slug: '48',
      ort: 'Lahr',
      jahr: 1986,
      venue: 'Altes Rathaus',
      titel: '5 x Malerei',
      untertitel: '',
      typ: 'Ausstellungsbeteiligung',
      von: null,
      bis: null,
      kommentar: '',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 50,
      slug: '50',
      ort: 'Offenburg',
      jahr: 1986,
      venue: 'Galerie Alte Wäscherei',
      titel: 'Liebeszeichen',
      untertitel: 'Künstlerkreis Ortenau',
      typ: 'Ausstellungsbeteiligung mit Katalog',
      von: null,
      bis: null,
      kommentar: '',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 49,
      slug: '49',
      ort: 'Karlsruhe',
      jahr: 1986,
      venue: 'Sparkasse',
      titel: 'Suche nach eigener Identität',
      untertitel: '',
      typ: 'Ausstellungsbeteiligung',
      von: null,
      bis: null,
      kommentar: '',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 46,
      slug: '46',
      ort: 'Karlsruhe',
      jahr: 1985,
      venue: 'Sparkasse',
      titel: 'Bildwelt der Figur',
      untertitel: '',
      typ: 'Ausstellungsbeteiligung',
      von: null,
      bis: null,
      kommentar: '',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 47,
      slug: '47',
      ort: 'Offenburg',
      jahr: 1985,
      venue: 'Galerie Alte Wäscherei',
      titel: 'Wasserzeichen',
      untertitel: 'Künstlerkreis Ortenau',
      typ: 'Ausstellungsbeteiligung mit Katalog',
      von: null,
      bis: null,
      kommentar: '',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 45,
      slug: '45',
      ort: 'Gengenbach',
      jahr: 1983,
      venue: 'Städtisches Museum Haus Löwenberg',
      titel: 'Vier Künstler aus der Ortenau',
      untertitel: '',
      typ: 'Ausstellungsbeteiligung',
      von: null,
      bis: null,
      kommentar: '',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
  ]
})
