<template>
  <main class="pb-16">
    <!-- <div class="sticky top-24">
      <h1 class="origin-bottom-right -rotate-90 bg-transparent p-2 text-right text-xl font-bold md:p-5">
        Ausstellungen
      </h1>
    </div> -->
    <div>
      <div class="sticky top-12">
        <h1 class="bg-white/90 p-2 text-xl font-bold md:p-5">Einzelausstellungen</h1>
      </div>

      <dl class="mx-auto max-w-screen-md pl-4 pr-12 text-gray-600 md:pl-8 md:pr-16">
        <template v-for="[year, exhibitions] in nachJahren" :key="year">
          <dt class="border-b border-black px-0 pb-1 pt-4 md:pt-6">{{ year }}</dt>

          <dd v-for="a in exhibitions" :key="a.id" class="mt-1.5 bg-white md:mt-2">
            <!-- <div class="flex w-12 self-start px-2">
                    <span v-if="i === 0">{{ a.jahr }}</span>
                </div> -->
            <div class="mr-auto flex-1 self-start pl-0 md:pl-4">
              <h4 class="overflow-hidden text-ellipsis text-sm text-gray-900">
                {{ a.titel }}
                <small v-if="a.untertitel" class="pl-2 text-sm font-normal text-gray-400">{{ a.untertitel }}</small>
              </h4>
              <!-- <h5 v-if="a.venue">
              {{ a.venue }}
              <span v-if="a.ort">, {{ a.ort }}</span>
            </h5> -->

              <!-- <small class="font-normal text-gray-500">{{ a.untertitel }}</small> -->

              <!-- <span class="ml-2 text-sm font-normal text-gray-400">{{ a.untertitel }}</span> -->

              <p class="overflow-hidden truncate text-sm font-light leading-none text-gray-500">
                {{ a.venue }}<span v-if="a.venue && a.ort">, </span>{{ a.ort }}
              </p>
            </div>
          </dd>
        </template>
      </dl>
    </div>

    <div class="pt-12">
      <div class="sticky top-12">
        <h1 class="bg-white/80 p-2 text-xl font-bold md:p-5">Beteiligungen</h1>
      </div>

      <dl class="mx-auto max-w-screen-md pl-4 pr-12 text-gray-600 md:pl-8 md:pr-16">
        <template v-for="[year, exhibitions] in betNachJahren" :key="year">
          <dt class="border-b border-black px-0 pb-1 pt-4 md:pt-6">{{ year }}</dt>

          <dd v-for="a in exhibitions" :key="a.id" class="mt-1.5 bg-white md:mt-2">
            <!-- <div class="flex w-12 self-start px-2">
                    <span v-if="i === 0">{{ a.jahr }}</span>
                </div> -->
            <div class="mr-auto flex-1 self-start pl-0 md:pl-4">
              <h4 class="overflow-hidden text-ellipsis text-sm text-gray-900">
                {{ a.titel }}
                <small v-if="a.untertitel" class="pl-2 text-sm font-normal text-gray-400">{{ a.untertitel }}</small>
              </h4>

              <p class="overflow-hidden truncate text-sm font-light leading-none text-gray-500">
                {{ a.venue }}<span v-if="a.venue && a.ort">, </span>{{ a.ort }}
              </p>
            </div>
          </dd>
        </template>
      </dl>
    </div>
  </main>
</template>

<script setup>
  // const { data: ausstellungen } = await useFetch('/api/ausstellungen?type=EINZEL', {
  //   key: 'einzelausstellungen',
  //   headers: {
  //     Cookie:
  //       'token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2ODg4MDk3OTIsIlVzZXJuYW1lIjoid29sZmdhbmcifQ._IoSIHrBkHpQXRNnyspcRVnA2eF8jPJjns8bZjQsKNA',
  //   },
  // })
  const ausstellungen = [
    {
      id: 126,
      slug: 'farben-des-lebens',
      ort: 'Freiburg',
      jahr: 2022,
      venue: 'c-punkt Münsterforum',
      titel: 'Farben des Lebens - Monochrome Bilder',
      untertitel: '',
      typ: 'Einzelausstellung mit Katalog',
      von: null,
      bis: null,
      kommentar: 'Farben des Lebens, monochrome Malerei, C-Punkt Münsterforum, Freiburg ',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 9,
      slug: '9',
      ort: 'Offenburg',
      jahr: 2019,
      venue: 'Dietrich-Bonhoeffer-Haus',
      titel: 'Kunst im Dietrich-Bonhoeffer-Haus',
      untertitel: 'Mit Axel Bleyer, Martin Sander, Gabi Streile, Rainer Nepita ',
      typ: 'Einzelausstellung',
      von: null,
      bis: null,
      kommentar: 'jeweils einzelne Ausstellungen in einzelnen Stockwerken ',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 7,
      slug: '2016-kunst-ort-kirche',
      ort: 'Ortenberg',
      jahr: 2016,
      venue: 'St. Bartholomäus Kirche',
      titel: 'Kunst Ort Kirche - Farbe. Aussagekraft im Bild ',
      untertitel: '',
      typ: 'Einzelausstellung',
      von: null,
      bis: null,
      kommentar: 'Kunst Ort Kirche, St. Bartholomäus Kirche, Orteberg',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 5,
      slug: '2013-rathaus',
      ort: 'Ortenberg',
      jahr: 2013,
      venue: 'Rathaus',
      titel: 'Malerei (Kunst im Rathaus)',
      untertitel: '',
      typ: 'Einzelausstellung',
      von: null,
      bis: null,
      kommentar: 'Kunst im Rathaus, Ortenberg',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 8,
      slug: 'monochrom',
      ort: 'Offenburg',
      jahr: 2013,
      venue: 'Galleries Ulrich Marx',
      titel: 'Monochrom',
      untertitel: '',
      typ: 'Einzelausstellung',
      von: null,
      bis: null,
      kommentar: 'Monochrom, Galleries Ulrich Marx, Offenburg',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 42,
      slug: '42',
      ort: 'March',
      jahr: 2008,
      venue: 'Kunstverein March',
      titel: 'Malerei / Fotografie',
      untertitel: 'Mit Géza Csizmazia',
      typ: 'Einzelausstellung',
      von: null,
      bis: null,
      kommentar: 'Malerei / Fotografie, mit Géza Csizmazia, Kunstverein, March',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 43,
      slug: '43',
      ort: 'Zunsweier',
      jahr: 2007,
      venue: 'Galerie am Berg',
      titel: 'Galerie am Berg',
      untertitel: '',
      typ: 'Einzelausstellung',
      von: null,
      bis: null,
      kommentar: 'Galerie am Berg, Zunsweier',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 44,
      slug: '44',
      ort: 'Kork',
      jahr: 2007,
      venue: 'Kunstforum',
      titel: 'Malerei und Fotografie',
      untertitel: 'mit Géza Csizmazia',
      typ: 'Einzelausstellung',
      von: null,
      bis: null,
      kommentar: 'Kunstforum Kork, mit Géza Csizmazia, Kork',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 40,
      slug: '40',
      ort: 'Renchen',
      jahr: 2006,
      venue: 'Galerie Owens',
      titel: 'Landschaften',
      untertitel: '',
      typ: 'Einzelausstellung',
      von: null,
      bis: null,
      kommentar: 'Landschaften, Galerie Owens, Renchen',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 41,
      slug: '41',
      ort: 'Haslach',
      jahr: 2006,
      venue: 'Kunstverein Mittleres Kinzigtal',
      titel: 'Natur und Architektur',
      untertitel: 'Mit Géza Csizmazia',
      typ: 'Einzelausstellung',
      von: null,
      bis: null,
      kommentar: 'Kunstverein Mittleres Kinzigtal, Mit Géza Csizmazia, Haslach',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 39,
      slug: '39',
      ort: 'Offenburg',
      jahr: 2004,
      venue: 'Galerie im Artforum, Künstlerkreis Ortenau',
      titel: 'In der Malerei unterwegs',
      untertitel: '',
      typ: 'Einzelausstellung',
      von: null,
      bis: null,
      kommentar: 'In der Malerei unterwegs, Galerie im Artforum, Künstlerkreis Ortenau, Offenburg',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 38,
      slug: '38',
      ort: 'Offenburg',
      jahr: 2002,
      venue: 'Klinikum Offenburg',
      titel: 'Paarweise',
      untertitel: 'Mit Albert Reichenbach',
      typ: 'Einzelausstellung',
      von: null,
      bis: null,
      kommentar: 'Paarweise, mit Albert Reichenbach, Offenburg',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 37,
      slug: '37',
      ort: 'Zunsweier',
      jahr: 2001,
      venue: 'Galerie am Berg',
      titel: 'Malerei \u0026 Keramikplastik',
      untertitel: 'Mit Manfred Emmenegger',
      typ: 'Einzelausstellung',
      von: null,
      bis: null,
      kommentar: 'Malerei \u0026 Keramikplastik, mit Manfred Emmenegger, Galerie am Berg, Zunsweier',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 36,
      slug: '36',
      ort: 'Offenburg',
      jahr: 1999,
      venue: 'Museum im Ritterhaus',
      titel: 'Natur',
      untertitel: 'Spiegel des Inneren',
      typ: 'Einzelausstellung',
      von: null,
      bis: null,
      kommentar: 'Natur - Spiegel des Inneren, Museum im Ritterhaus, Offenburg',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 95,
      slug: '95',
      ort: 'Offenburg',
      jahr: 1998,
      venue: 'Galerie „Alte Wäscherei“',
      titel: '„Arbeitszeit“',
      untertitel: 'Mit Csizmazia, Emmenegger, Teipelke, Schultz-Koernig',
      typ: 'Einzelausstellung',
      von: null,
      bis: null,
      kommentar: '',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 35,
      slug: '35',
      ort: 'Bruchsal',
      jahr: 1997,
      venue: 'Städtische Galerie',
      titel: 'Malerei \u0026 Zeichnung',
      untertitel: '',
      typ: 'Einzelausstellung',
      von: null,
      bis: null,
      kommentar: 'Malerei \u0026 Zeichnung, Städtische Galerie, Bruchsal',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 34,
      slug: '34',
      ort: 'Bad Krozingen',
      jahr: 1997,
      venue: 'Herzzentrum',
      titel: 'Kunst in der Klinik',
      untertitel: '',
      typ: 'Einzelausstellung',
      von: null,
      bis: null,
      kommentar: 'Kunst in der Klinik, Herzzentrum, Bad Krozingen',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 33,
      slug: '33',
      ort: 'Karlsruhe',
      jahr: 1995,
      venue: 'Galerie Akzente',
      titel: 'Malerei',
      untertitel: '',
      typ: 'Einzelausstellung',
      von: null,
      bis: null,
      kommentar: 'Malerei, Galerie Akzente, Karlsruhe',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 31,
      slug: '31',
      ort: 'Mainz',
      jahr: 1994,
      venue: 'Galerie der Stadt Mainz',
      titel: 'Brückenturm',
      untertitel: '',
      typ: 'Einzelausstellung',
      von: null,
      bis: null,
      kommentar: 'Brückenturm, Galerie der Stadt Mainz, Mainz',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 24,
      slug: '24',
      ort: 'Lahr',
      jahr: 1994,
      venue: 'Galerie Wild',
      titel: 'Malerei',
      untertitel: 'Bilder 1992 - 1994',
      typ: 'Einzelausstellung',
      von: null,
      bis: null,
      kommentar: 'Malerei - Bilder 1992 - 1994, Galerie Wild, Lahr',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 32,
      slug: '32',
      ort: 'Schramberg',
      jahr: 1994,
      venue: 'Podium Kunst',
      titel: 'Malerei',
      untertitel: '',
      typ: 'Einzelausstellung',
      von: null,
      bis: null,
      kommentar: 'Malerei, Podium Kunst, Schramberg',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 30,
      slug: '30',
      ort: 'Rohrdorf',
      jahr: 1993,
      venue: 'Galerie Györfi',
      titel: 'Malerei',
      untertitel: 'Mit Heidi Kucher und Guido Kucznierz',
      typ: 'Einzelausstellung',
      von: null,
      bis: null,
      kommentar: '',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 29,
      slug: '29',
      ort: 'Strasbourg',
      jahr: 1993,
      venue: 'Galerie du Faisan',
      titel: 'Malerei',
      untertitel: '',
      typ: 'Einzelausstellung',
      von: null,
      bis: null,
      kommentar: 'Malerei, Galerie du Faisan, Strasbourg',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 26,
      slug: '26',
      ort: 'Haslach',
      jahr: 1991,
      venue: 'Kunstverein Mittleres Kinzigtal, Kapuzinerkloster',
      titel: 'Malerei',
      untertitel: '',
      typ: 'Einzelausstellung',
      von: null,
      bis: null,
      kommentar: 'Malerei, Kunstverein Mittleres Kinzigtal, Kapuzinerkloster, Haslach',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 27,
      slug: '27',
      ort: 'Zell a. H.',
      jahr: 1991,
      venue: 'Walter-Bischoff-Galerie',
      titel: '',
      untertitel: '',
      typ: 'Einzelausstellung',
      von: null,
      bis: null,
      kommentar: 'Walter-Bischoff-Galerie, Zell a. H.',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 25,
      slug: '25',
      ort: 'Offenburg',
      jahr: 1989,
      venue: 'Staatliches Schulamt',
      titel: '',
      untertitel: '',
      typ: 'Einzelausstellung',
      von: null,
      bis: null,
      kommentar: 'Staatliches Schulamt, Offenburg',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 23,
      slug: '23',
      ort: 'Karlsruhe',
      jahr: 1989,
      venue: 'Künstlerhaus',
      titel: 'Malerei',
      untertitel: 'Mit Rainer Nepita und Werner Schmidt',
      typ: 'Einzelausstellung',
      von: null,
      bis: null,
      kommentar: 'Malerei, mit Rainer Nepita und Werner Schmidt, Künstlerhaus, Karlsruhe',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 22,
      slug: '22',
      ort: 'Freiburg',
      jahr: 1988,
      venue: 'Galerie im Schwarzen Kloster',
      titel: 'Malerei',
      untertitel: 'Mit Rainer Nepita und Werner Schmidt',
      typ: 'Einzelausstellung',
      von: null,
      bis: null,
      kommentar: 'Malerei, mit Rainer Nepita und Werner Schmidt, Schwarzes Kloster, Freiburg',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 2,
      slug: 'durchgang',
      ort: 'Offenburg',
      jahr: 1987,
      venue: 'Stadthalle / Sparkasse',
      titel: 'Durchgang',
      untertitel: 'Mit R. Braxmaier, H. Heider, W. Schmidt \u0026 G. Streile ',
      typ: 'Einzelausstellung',
      von: null,
      bis: null,
      kommentar:
        '1986 war die neue Garage neben der Sparkasse in Offenburg fertig. Zwischen ihr und der Stadthalle war ein Durchgang mit eingeplant worden. \r\n In diesem Durchgang haben sich große Flächen zur Ausgestaltung angeboten. Die Stadt Offenburg unter dem damaligen Oberbürgermeister Martin Grüber hat unserem damals neugegründeten Künstlerkreis (Galerie „Alte Wäscherei“, 1985 eröffnet) den Auftrag gegeben, diesen Durchgang künstlerisch zu gestalten. \r\n Nach der Fertigstellung dieser künstlerischen Arbeit wurde im Januar 1987 im Foyer der Stadthalle eine Ausstellung der beteiligten fünf Künstler/innen eröffnet.',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 21,
      slug: '21',
      ort: 'Offenburg',
      jahr: 1987,
      venue: 'Werkstattgalerie "Alte Wäscherei"',
      titel: 'Bilder von 1985 - 1987',
      untertitel: '',
      typ: 'Einzelausstellung',
      von: null,
      bis: null,
      kommentar: 'Bilder von 1985 - 1987, Werkstattgalerie "Alte Wäscherei", Offenburg',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 20,
      slug: '20',
      ort: 'Amriswil / Schweiz',
      jahr: 1986,
      venue: 'Schloss Hagenwil',
      titel: 'Malerei auf Papier',
      untertitel: '',
      typ: 'Einzelausstellung',
      von: null,
      bis: null,
      kommentar: 'Malerei auf Papier, Schloss Hagenwil, Amriswil, Schweiz',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 19,
      slug: '19',
      ort: 'Meersburg',
      jahr: 1985,
      venue: 'Barockschloss',
      titel: '„Figurenbilder, Landschaften, Stilleben“',
      untertitel: 'Städtische Galerie im Barockschloss',
      typ: 'Einzelausstellung',
      von: null,
      bis: null,
      kommentar: '',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 1,
      slug: '1',
      ort: 'Offenburg',
      jahr: 1981,
      venue: 'Städtisches Verkehrsamt',
      titel: 'Gemälde, Zeichnungen, Radierungen, Aquarelle',
      untertitel: '',
      typ: 'Einzelausstellung',
      von: null,
      bis: null,
      kommentar: '',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
  ]

  // const { data: beteiligungen } = await useFetch('/api/ausstellungen?type=B', {
  //   key: 'ausstellungsbeteiligungen',

  //   headers: {
  //     Cookie:
  //       'token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2ODg4MDk3OTIsIlVzZXJuYW1lIjoid29sZmdhbmcifQ._IoSIHrBkHpQXRNnyspcRVnA2eF8jPJjns8bZjQsKNA',
  //   },
  // })

  const beteiligungen = [
    {
      id: 6,
      slug: '6',
      ort: 'Schramberg',
      jahr: 2018,
      venue: 'Galerie Podium Kunst im Schloß',
      titel: '40 Jahre Podium Kunst ',
      untertitel: 'Jubiläumsausstellung 2018',
      typ: 'Ausstellungsbeteiligung',
      von: null,
      bis: null,
      kommentar: '',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 13,
      slug: '13',
      ort: 'Durbach',
      jahr: 2017,
      venue: 'Museum Hurrle',
      titel: 'Auf unbekanntem Terrain.',
      untertitel: 'Landschaft in der Kunst nach 1945',
      typ: 'Ausstellungsbeteiligung',
      von: null,
      bis: null,
      kommentar:
        'Europe | Exhibitions | news | artports | September 23, 2017 |\r\nFortschritt und Zeitgeist formen und verändern seit Jahrhunderten unsere Umwelt. Spätestens seit der industriellen Revolution des 19. Jahrhunderts vollzieht sich dieser Wandel in reißender Geschwindigkeit. Mit der Expansion des Städtischen haben sich neue Qualitäten und Perspektiven entwickelt, durch die sich Landschaft heute weit über das vordergründig Ländliche hinaus in weite Lebensbereiche erstreckt.\u2028Mit der Zäsur des 2. Weltkrieges erschien das gegenständliche Abbild in der Kunst als nicht mehr zeitgemäß, und für annähernd zwei Jahrzehnte avancierte die Abstraktion zur dominierenden Weltsprache in der Kunst. Trotz dieses radikalen Bruches blieb das Motiv der Landschaft eine wichtige Referenz und wird in einer Vielzahl ungegenständlicher Werke reflektiert.\u2028Zu dieser Zeit trat zur geografisch definierten Landschaft ein neuer, sozial und kulturell konstruierter Landschaftsbegriff hinzu. Er orientiert sich weniger an einer physisch realen Situation, sondern es handelt sich vielmehr um eine Interpretation der wahrgenommenen Welt, die durch Prägung und Erfahrung bestimmt ist. Durch ihn konnte die Landschaft in den Nachkriegsjahren in Bereiche des Ungegenständlichen vordringen, bevor sie zu Beginn der sechziger Jahre als erkennbares Motiv in die Kunst zurückkehren sollte.\r\n\r\nIn vier Kapiteln und mit über 100 Wlerken verschiedenster Künstler spürt die von dem Berliner Kunsthistoriker Ronald Puff kuratierte Ausstellung der Reflexion von Landschaft in der Kunst seit 1945 nach und lässt Schritt für Schritt sichtbar werden, wie sie sich vom mimetischen Abbild hin zu einer Vorstellung entwickelte, die sich jenseits des Abbildes manifestiert.\r\n\r\nDen Auftakt zur Ausstellung bildet das Kapitel Dokument, das sich der Objektivität und den Facetten des Realismus in der Landschaftsdarstellung zuwendet. Dabei reicht das Panorama über fotografische Arbeiten von Michael Wesely und Ottmar Hörl bis zum brillanten Hyperrealismus von Bernd Schwering und Andreas Orosz.\u2028Die unter der Überschrift Expression versammelten Positionen zeichnen ein Landschaftsbild, in dem das Motiv zum Spiegel eines weitreichenden Diskurses wird. Beispielsweise wird die politische Lage der BRD oder die Situation des geteilten Berlin ebenso reflektiert wie das gesellschaftliche und kulturelle Umfeld innerhalb der DDR. Hiervon entwerfen die kraftvollen Werke von unter anderem Georg Baselitz, K.H. Hödicke, Wolfgang Mattheuer oder Hans Scheib ein aufschlussreiches Bild.\u2028Schließlich widmet sich das Kapitel Poesie, das als letzte Station dem augenfälligen Abbild von Landschaft verpflichtet ist, den nichtsprachlichen, poetischen Qualitäten.\u2028In den berührenden Werken von Gerhard Altenbourg, Horst Janssen und Richard Oelze eröffnen sich Landschaften, die zwischen Gegenständlichkeit und Abstraktion oszillieren und deren Ausdruckskraft sich dem rational Fass- und Beschreibbaren entziehen.\u2028Diese Werke bilden die Brücke zum Abschluss der Ausstellung mit dem Titel Jenseits des Abbildes, in dem herausragende Werke der Nachkriegsmoderne, von Willi Baumeister über Bernard Schulze und Gotthard Graubner bis zu bedeutenden Positionen der Gegenwart wie Pia Fries, Per Kirkeby, Olav Christopher Jenssen, Hanspeter Münch und Eugene Leroy zeigen, dass Landschaft auch in der Ungegenständlichkeit ein wichtiges und reflektiertes Thema darstellt, das über sich selbst hinausweist.\r\n\r\nPR: Sammlung Hurrle, Durbach\r\nAusstellung vom 16. September 2017 bis 4. Februar 2018\r\n77770\u2028Museum für aktuelle Kunst\u2028Sammlung Hurrle Durbach\u2028Vier Jahreszeiten Durbach GmbH \u0026 Co. KGAlmstraße 49\u2028D-77770 Durbach',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 14,
      slug: '14',
      ort: 'Rastatt',
      jahr: 2015,
      venue: 'Städt. Galerie Fruchthalle',
      titel: 'Sammlung Westermann',
      untertitel: '',
      typ: 'Ausstellungsbeteiligung',
      von: null,
      bis: null,
      kommentar: '',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 128,
      slug: '128',
      ort: '',
      jahr: 2014,
      venue: '',
      titel: '30 Jahre',
      untertitel: 'Kunstverein Mittleres Kinzigtal',
      typ: 'Ausstellungsbeteiligung mit Katalog',
      von: null,
      bis: null,
      kommentar: '',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 10,
      slug: '10',
      ort: 'Schramberg???',
      jahr: 2012,
      venue: 'Landesgartenschau',
      titel: 'Natur und Landschaft heute',
      untertitel: 'Malerei aus dem Südwesten',
      typ: 'Ausstellungsbeteiligung',
      von: null,
      bis: null,
      kommentar: '',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 17,
      slug: '17',
      ort: 'Nagold',
      jahr: 2012,
      venue: 'Teufel-Areal, Landesgartenschau',
      titel: 'Natur und Landschaft heute',
      untertitel: 'Malerei aus dem Südwesten',
      typ: 'Ausstellungsbeteiligung',
      von: null,
      bis: null,
      kommentar: '',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 125,
      slug: '125',
      ort: 'Offenburg',
      jahr: 2011,
      venue: 'Galerie im Artforum',
      titel: '"Landschaft"',
      untertitel: '',
      typ: 'Ausstellungsbeteiligung',
      von: null,
      bis: null,
      kommentar: '',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 12,
      slug: '12',
      ort: 'Offenburg',
      jahr: 2010,
      venue: 'Städtische Galerie',
      titel: 'Aus dem Fundus',
      untertitel: 'Die Offenburger Kunstsammlung stellt sich vor',
      typ: 'Ausstellungsbeteiligung',
      von: null,
      bis: null,
      kommentar: '',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 11,
      slug: '11',
      ort: 'Ettenheimmünster',
      jahr: 2010,
      venue: 'Galerie Linda Treiber',
      titel: 'Kunstschaffende aus der Ortenau',
      untertitel: '',
      typ: 'Ausstellungsbeteiligung',
      von: null,
      bis: null,
      kommentar: '',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 16,
      slug: '16',
      ort: 'Rastatt',
      jahr: 2009,
      venue: 'Historisches Rathaus',
      titel: 'Revolution in der Box',
      untertitel: 'Tag der Badischen Revolution (Sammlung Westermann)',
      typ: 'Ausstellungsbeteiligung',
      von: null,
      bis: null,
      kommentar: '',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 15,
      slug: '15',
      ort: 'Haslach',
      jahr: 2009,
      venue: 'Kunstverein Mittleres Kinzigtal, Kapuzinerkloster',
      titel: 'Schwarzwaldbild 4',
      untertitel: '',
      typ: 'Ausstellungsbeteiligung',
      von: null,
      bis: null,
      kommentar: '',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 124,
      slug: '124',
      ort: 'Baden-Baden',
      jahr: 2009,
      venue: 'Altes Dampfbad',
      titel: '"Vasen"',
      untertitel: '',
      typ: 'Ausstellungsbeteiligung',
      von: null,
      bis: null,
      kommentar: '',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 127,
      slug: '127',
      ort: 'Offenburg',
      jahr: 2008,
      venue: 'Galerie im Artforum',
      titel: 'Geteilt',
      untertitel: 'Künsterkreis Ortenau',
      typ: 'Ausstellungsbeteiligung',
      von: null,
      bis: null,
      kommentar: '',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 123,
      slug: '123',
      ort: 'Lauterbach',
      jahr: 2007,
      venue: 'Galerie Kimmich',
      titel: 'Landschaft im 21. Jahrhundert',
      untertitel: '',
      typ: 'Ausstellungsbeteiligung',
      von: null,
      bis: null,
      kommentar: '',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 122,
      slug: '122',
      ort: 'Olsztyn, Polen',
      jahr: 2007,
      venue: 'Galeria Sztuki ',
      titel: '"Most sztuki - Kunst-Brücke"',
      untertitel: '',
      typ: 'Ausstellungsbeteiligung mit Katalog',
      von: null,
      bis: null,
      kommentar: '',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 119,
      slug: '119',
      ort: 'Freiburg',
      jahr: 2006,
      venue: 'E-Werk',
      titel: 'Künstlerkreis Ortenau',
      untertitel: '',
      typ: 'Ausstellungsbeteiligung',
      von: null,
      bis: null,
      kommentar: '',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 120,
      slug: '120',
      ort: 'Fürstenwalde',
      jahr: 2006,
      venue: 'Galerie Altes Rathaus',
      titel: '7. Miniatur in der bildenden Kunst',
      untertitel: '',
      typ: 'Ausstellungsbeteiligung mit Katalog',
      von: null,
      bis: null,
      kommentar: '',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 121,
      slug: '121',
      ort: 'Zell a.H.',
      jahr: 2006,
      venue: 'Villa Haiss Museum',
      titel: '„40 Künstler der Ortenau“',
      untertitel: '',
      typ: 'Ausstellungsbeteiligung',
      von: null,
      bis: null,
      kommentar: '',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 118,
      slug: '118',
      ort: 'Offenburg',
      jahr: 2005,
      venue: 'Galerie im Gewölbe',
      titel: '„Formart“',
      untertitel: '',
      typ: 'Ausstellungsbeteiligung',
      von: null,
      bis: null,
      kommentar: '',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 117,
      slug: '117',
      ort: 'Ettlingen',
      jahr: 2004,
      venue: 'Museum Schloß Ettlingen',
      titel: '„Landschaft – Zeitgenössische Positionen“',
      untertitel: '',
      typ: 'Ausstellungsbeteiligung mit Katalog',
      von: null,
      bis: null,
      kommentar: '',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 116,
      slug: '116',
      ort: 'Schramberg',
      jahr: 2002,
      venue: 'Galerie Podium Kunst im Schloß',
      titel: '„Vergangenheit“',
      untertitel: '',
      typ: 'Ausstellungsbeteiligung mit Katalog',
      von: null,
      bis: null,
      kommentar: '',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 114,
      slug: '114',
      ort: 'Strasbourg',
      jahr: 2002,
      venue: "Zone d' art",
      titel: '„Duell?“',
      untertitel: 'Accrochage Franco-Allemand',
      typ: 'Ausstellungsbeteiligung',
      von: null,
      bis: null,
      kommentar: '',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 113,
      slug: '113',
      ort: 'Offenburg',
      jahr: 2002,
      venue: 'Galerie im Artforum',
      titel: '„Haute Couture“',
      untertitel: '',
      typ: 'Ausstellungsbeteiligung',
      von: null,
      bis: null,
      kommentar: '',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 115,
      slug: '115',
      ort: 'Berlin',
      jahr: 2002,
      venue: 'Landesvertretung Baden-Württemberg',
      titel: 'Installation des Künstlerkreises Ortenau',
      untertitel: '',
      typ: 'Ausstellungsbeteiligung',
      von: null,
      bis: null,
      kommentar: '',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 112,
      slug: '112',
      ort: 'Lahr',
      jahr: 2001,
      venue: 'Galerie Wild',
      titel: '„Neue Ernte“',
      untertitel: '',
      typ: 'Ausstellungsbeteiligung',
      von: null,
      bis: null,
      kommentar: '',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 110,
      slug: '110',
      ort: 'Baden-Baden',
      jahr: 2001,
      venue: 'Staatliche Kunsthalle',
      titel: '„Was mir gefällt“',
      untertitel: 'Gesellschaft der Freunde junger Kunst',
      typ: 'Ausstellungsbeteiligung',
      von: null,
      bis: null,
      kommentar: '',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 108,
      slug: '108',
      ort: 'Freiburg',
      jahr: 2001,
      venue: 'Städtische Galerie Schwarzes Kloster',
      titel: '„Zeichnung“',
      untertitel: '',
      typ: 'Ausstellungsbeteiligung',
      von: null,
      bis: null,
      kommentar: '',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 111,
      slug: '111',
      ort: 'Renchen',
      jahr: 2001,
      venue: 'Galerie Owens',
      titel: '„Künstlerkreis Ortenau“',
      untertitel: '',
      typ: 'Ausstellungsbeteiligung',
      von: null,
      bis: null,
      kommentar: '',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 109,
      slug: '109',
      ort: 'Haslach',
      jahr: 2001,
      venue: 'Kunstverein Mittleres Kinzigtal, Kapuzinerkloster',
      titel: 'Schwarzwaldbild 2',
      untertitel: '',
      typ: 'Ausstellungsbeteiligung',
      von: null,
      bis: null,
      kommentar: '',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 106,
      slug: '106',
      ort: 'Offenburg',
      jahr: 2000,
      venue: 'Galerie Artforum',
      titel: '„Reisen“',
      untertitel: 'Künstlerkreis Ortenau',
      typ: 'Ausstellungsbeteiligung',
      von: null,
      bis: null,
      kommentar: '',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 104,
      slug: '104',
      ort: 'Tettnang',
      jahr: 2000,
      venue: 'Galerie im Torschloß',
      titel: '„Malerische Malerei“',
      untertitel: '',
      typ: 'Ausstellungsbeteiligung',
      von: null,
      bis: null,
      kommentar: '',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 107,
      slug: '107',
      ort: 'Schramberg',
      jahr: 2000,
      venue: 'Galerie Podium Kunst im Schloss',
      titel: '„Tanne und Baum“',
      untertitel: '',
      typ: 'Ausstellungsbeteiligung',
      von: null,
      bis: null,
      kommentar: '',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 105,
      slug: '105',
      ort: 'Baden-Baden',
      jahr: 2000,
      venue: 'Kunsthalle',
      titel: '„Compakt 2000“',
      untertitel: 'Gesellschaft der Freunde junger Kunst',
      typ: 'Ausstellungsbeteiligung',
      von: null,
      bis: null,
      kommentar: '',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 98,
      slug: '98',
      ort: 'Strasbourg',
      jahr: 1999,
      venue: 'Messe',
      titel: "„st'art 99“",
      untertitel: 'Vertreten durch Galerie Wild',
      typ: 'Ausstellungsbeteiligung',
      von: null,
      bis: null,
      kommentar: '',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 101,
      slug: '101',
      ort: 'Bonn',
      jahr: 1999,
      venue: 'Vertretung des Landes Baden-Württemberg',
      titel: '„Unterwegs“',
      untertitel: 'Landesverband BBK Baden-Württemberg',
      typ: 'Ausstellungsbeteiligung',
      von: null,
      bis: null,
      kommentar: '',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 99,
      slug: '99',
      ort: 'Lahr',
      jahr: 1999,
      venue: 'Städtische Galerie im Alten Rathaus',
      titel: '„Kunst aus Wellpappe“',
      untertitel: '',
      typ: 'Ausstellungsbeteiligung mit Katalog',
      von: null,
      bis: null,
      kommentar: '',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 102,
      slug: '102',
      ort: 'St. Andreasberg',
      jahr: 1999,
      venue: 'Galerie Rathaus-Scheune',
      titel: '„Natur und Mensch“',
      untertitel: '',
      typ: 'Ausstellungsbeteiligung mit Katalog',
      von: null,
      bis: null,
      kommentar: '',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 100,
      slug: '100',
      ort: 'Rastatt',
      jahr: 1999,
      venue: 'Städtische Galerie Fruchthalle',
      titel: '„Revolution in der Box“',
      untertitel: 'Die Badische Revolution 1848/49 in der Sammlung Westermann',
      typ: 'Ausstellungsbeteiligung mit Katalog',
      von: null,
      bis: null,
      kommentar: '',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 103,
      slug: '103',
      ort: 'Offenburg',
      jahr: 1999,
      venue: 'Oberrheinmesse',
      titel: 'Ortenauer Kunstforum',
      untertitel: '',
      typ: 'Ausstellungsbeteiligung',
      von: null,
      bis: null,
      kommentar: '',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 93,
      slug: '93',
      ort: 'Baden-Baden',
      jahr: 1998,
      venue: 'Galerie der Gesellschaft der Freunde junger Kunst',
      titel: '„Druck“',
      untertitel: 'Gesellschaft der Freunde junger Kunst',
      typ: 'Ausstellungsbeteiligung',
      von: null,
      bis: null,
      kommentar: '',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 97,
      slug: '97',
      ort: 'Halberstadt \u0026 Weißenfels',
      jahr: 1998,
      venue: 'Museum im Gleimhaus \u0026Schloßmuseum',
      titel: '„Neues zu G.A. Bürger“',
      untertitel: '',
      typ: 'Ausstellungsbeteiligung',
      von: null,
      bis: null,
      kommentar: '',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 91,
      slug: '91',
      ort: 'Strasbourg',
      jahr: 1998,
      venue: "Clinique de l' Orangerie",
      titel: '„Paysages“',
      untertitel: '',
      typ: 'Ausstellungsbeteiligung',
      von: null,
      bis: null,
      kommentar: '',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 96,
      slug: '96',
      ort: 'Offenburg',
      jahr: 1998,
      venue: 'Galerie im Klinikum',
      titel: '????',
      untertitel: '',
      typ: 'Ausstellungsbeteiligung',
      von: null,
      bis: null,
      kommentar: '',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 94,
      slug: '94',
      ort: 'Offenburg',
      jahr: 1998,
      venue: 'Landratsamt',
      titel: 'Kunstsammlung des Ortenaukreises',
      untertitel: '',
      typ: 'Ausstellungsbeteiligung',
      von: null,
      bis: null,
      kommentar: '',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 90,
      slug: '90',
      ort: 'Strasbourg',
      jahr: 1998,
      venue: 'Kunstmesse',
      titel: "„st' art 98“",
      untertitel: 'Vertreten durch Galerie Wild',
      typ: 'Ausstellungsbeteiligung',
      von: null,
      bis: null,
      kommentar: '',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 92,
      slug: '92',
      ort: 'Colmar',
      jahr: 1998,
      venue: 'Parc des Expositions de Colmar',
      titel: '„Les Toques Modèles“',
      untertitel: '',
      typ: 'Ausstellungsbeteiligung',
      von: null,
      bis: null,
      kommentar: '',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 85,
      slug: '85',
      ort: 'Haslach',
      jahr: 1997,
      venue: 'Kunstverein Mittleres Kinzigtal, Kapuzinerkloster',
      titel: '„Schwarzwaldbild“',
      untertitel: '',
      typ: 'Ausstellungsbeteiligung',
      von: null,
      bis: null,
      kommentar: '',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 86,
      slug: '86',
      ort: 'Höchstadt an der Aisch',
      jahr: 1997,
      venue: 'Kunstverein',
      titel: '„Kunst im Schloß“',
      untertitel: '',
      typ: 'Ausstellungsbeteiligung',
      von: null,
      bis: null,
      kommentar: '',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 89,
      slug: '89',
      ort: 'Freiburg',
      jahr: 1997,
      venue: 'Städtische Galerie im Schwarzen Kloster',
      titel: '„Der Kunstsalon“',
      untertitel: 'BBK Südbaden',
      typ: 'Ausstellungsbeteiligung',
      von: null,
      bis: null,
      kommentar: '',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 88,
      slug: '88',
      ort: 'Lahr',
      jahr: 1997,
      venue: 'Galerie Wild',
      titel: '„Kunst Herbst – Herbst Kunst“',
      untertitel: '',
      typ: 'Ausstellungsbeteiligung',
      von: null,
      bis: null,
      kommentar: '',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 87,
      slug: '87',
      ort: 'Achberg',
      jahr: 1997,
      venue: 'Schloß Achberg',
      titel: '„Trotz und Übermut“',
      untertitel: 'Sammlung Horn',
      typ: 'Ausstellungsbeteiligung mit Katalog',
      von: null,
      bis: null,
      kommentar: '',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 82,
      slug: '82',
      ort: 'Strasbourg',
      jahr: 1996,
      venue: 'Kunstmesse',
      titel: "„st' art 96“",
      untertitel: 'Vertreten durch Galerie Wild',
      typ: 'Ausstellungsbeteiligung',
      von: null,
      bis: null,
      kommentar: '',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 79,
      slug: '79',
      ort: 'Freiburg',
      jahr: 1995,
      venue: 'Städtische Galerie im Schwarzen Kloster',
      titel: 'Schwarzwald jetzt und hier',
      untertitel: '',
      typ: 'Ausstellungsbeteiligung',
      von: null,
      bis: null,
      kommentar: '',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 81,
      slug: '81',
      ort: 'Offenburg',
      jahr: 1995,
      venue: 'Galerie Alte Wäscherei',
      titel: 'Zeitgenössische Kunst im sakralen Raum - Ein Dialog',
      untertitel: 'Künstlerkreis Ortenau',
      typ: 'Ausstellungsbeteiligung mit Katalog',
      von: null,
      bis: null,
      kommentar: '',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 80,
      slug: '80',
      ort: 'Strasbourg',
      jahr: 1995,
      venue: 'Galerie Faisant',
      titel: 'Hommage à Marcel Cahn',
      untertitel: '',
      typ: 'Ausstellungsbeteiligung',
      von: null,
      bis: null,
      kommentar: '',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 77,
      slug: '77',
      ort: 'Offenburg',
      jahr: 1994,
      venue: 'Städtische Galerie im Spitalspeicher',
      titel: 'Zeitgenössische Kunst in der Ortenau',
      untertitel: '',
      typ: 'Ausstellungsbeteiligung',
      von: null,
      bis: null,
      kommentar: '',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 76,
      slug: '76',
      ort: 'Offenburg',
      jahr: 1994,
      venue: 'Fachhochschule',
      titel: 'Mensch und Technik',
      untertitel: '',
      typ: 'Ausstellungsbeteiligung mit Katalog',
      von: null,
      bis: null,
      kommentar: '',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 75,
      slug: '75',
      ort: 'Augsburg',
      jahr: 1994,
      venue: 'Rathaus',
      titel: 'Menschen und Rechte.',
      untertitel: 'Hommage à Heinrich Heine',
      typ: 'Ausstellungsbeteiligung mit Katalog',
      von: null,
      bis: null,
      kommentar: '',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 78,
      slug: '78',
      ort: 'Böblingen',
      jahr: 1994,
      venue: 'Galerie contact',
      titel: 'verpackt, verschnürt, verschickt',
      untertitel: '',
      typ: 'Ausstellungsbeteiligung mit Katalog',
      von: null,
      bis: null,
      kommentar: '',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 74,
      slug: '74',
      ort: 'Karlsruhe',
      jahr: 1992,
      venue: 'Kongresszentrum',
      titel: 'Und sie bewegt sich doch',
      untertitel: 'Bundesverband Bildender Künstler',
      typ: 'Ausstellungsbeteiligung mit Katalog',
      von: null,
      bis: null,
      kommentar: '',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 71,
      slug: '71',
      ort: 'Kronach',
      jahr: 1992,
      venue: 'Städtische Galerie',
      titel: 'Lucas-Cranach-Preis „Menschenbilder“',
      untertitel: '',
      typ: 'Ausstellungsbeteiligung mit Katalog',
      von: null,
      bis: null,
      kommentar: '',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 70,
      slug: '70',
      ort: 'St. Petersburg \u0026 Petrosawodsk \u0026 Simferopol',
      jahr: 1992,
      venue: 'Haus der Freundschaft',
      titel: 'Künstler aus Baden-Württemberg',
      untertitel: '',
      typ: 'Ausstellungsbeteiligung',
      von: null,
      bis: null,
      kommentar: '',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 72,
      slug: '72',
      ort: 'Freiburg',
      jahr: 1992,
      venue: 'IHK',
      titel: 'Bilder aus Südbaden',
      untertitel: ' Kunstsammlung IHK',
      typ: 'Ausstellungsbeteiligung mit Katalog',
      von: null,
      bis: null,
      kommentar: '',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 73,
      slug: '73',
      ort: 'Offenburg',
      jahr: 1992,
      venue: 'Galerie Alte Wäscherei',
      titel: 'Die Farbe Grau',
      untertitel: 'Künstlerkreis Ortenau',
      typ: 'Ausstellungsbeteiligung',
      von: null,
      bis: null,
      kommentar: '',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 67,
      slug: '67',
      ort: 'Wiesbaden',
      jahr: 1991,
      venue: ' Kunsthaus',
      titel: '10 x 10 x 10',
      untertitel: 'quadratisch - eckig - Kunst',
      typ: 'Ausstellungsbeteiligung mit Katalog',
      von: null,
      bis: null,
      kommentar: '',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 66,
      slug: '66',
      ort: 'Kehl',
      jahr: 1991,
      venue: 'Badische Stahlwerke',
      titel: 'Kunst aus Baden und dem Elsaß',
      untertitel: '',
      typ: 'Ausstellungsbeteiligung mit Katalog',
      von: null,
      bis: null,
      kommentar: '',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 69,
      slug: '69',
      ort: 'Offenburg',
      jahr: 1991,
      venue: 'Städtische Galerie im Spitalspeicher',
      titel: 'Kunst der Region',
      untertitel: '',
      typ: 'Ausstellungsbeteiligung',
      von: null,
      bis: null,
      kommentar: '',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 68,
      slug: '68',
      ort: 'Baden-Baden',
      jahr: 1991,
      venue: ' Gesellschaft der Freunde junger Kunst',
      titel: 'Landschaft – faxen',
      untertitel: '',
      typ: 'Ausstellungsbeteiligung',
      von: null,
      bis: null,
      kommentar: '',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 63,
      slug: '63',
      ort: 'Oberwil/Basel',
      jahr: 1990,
      venue: '',
      titel: 'Basellandschaftliche Kunstausstellung',
      untertitel: '',
      typ: 'Ausstellungsbeteiligung',
      von: null,
      bis: null,
      kommentar: '',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 65,
      slug: '65',
      ort: 'Baden-Baden',
      jahr: 1990,
      venue: 'Galerie der Gesellschaft der Freunde junger Kunst',
      titel: 'Blättern',
      untertitel: 'Gesellschaft der Freunde junger Kunst',
      typ: 'Ausstellungsbeteiligung',
      von: null,
      bis: null,
      kommentar: '',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 62,
      slug: '62',
      ort: "Civitella d'Agliano, Italien",
      jahr: 1990,
      venue: 'Castello',
      titel: 'Natura',
      untertitel: '',
      typ: 'Ausstellungsbeteiligung mit Katalog',
      von: null,
      bis: null,
      kommentar: '',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 60,
      slug: '60',
      ort: 'Mülheim \u0026 Gelsenkirchen',
      jahr: 1990,
      venue: 'Städtische Museen',
      titel: 'Der aufrechte Gang',
      untertitel: '',
      typ: 'Ausstellungsbeteiligung mit Katalog',
      von: null,
      bis: null,
      kommentar: 'Termine: 4.-17.9.1989 Unna Ausstellungshalle Kurpark ...',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 64,
      slug: '64',
      ort: 'Offenburg',
      jahr: 1990,
      venue: 'Galerie Alte Wäscherei',
      titel: 'Pas de deux',
      untertitel: 'Künstlerkreis Ortenau',
      typ: 'Ausstellungsbeteiligung',
      von: null,
      bis: null,
      kommentar: '',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 61,
      slug: '61',
      ort: 'Strasbourg',
      jahr: 1990,
      venue: 'Ancienne Laiterie',
      titel: 'Autoportraits – Repères',
      untertitel:
        'avec Jean-Louis CHARVOT, Louis DANICHER, Jean-Francois HEINTZ, Erling JOHANSSON, Iris KRAMER, Christophe MEYER, MORZUCH, Suzanne OBRECHT, Bernard QUESNIAUX, Hubert RIEBER, Marie SESTER, Jo SIMON, Agnès THUIN',
      typ: 'Ausstellungsbeteiligung mit Katalog',
      von: null,
      bis: null,
      kommentar: 'Im Rahmen einer Veranstaltungsreihe zum 100. Todestag von Vincent van Gogh',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 59,
      slug: '59',
      ort: 'Offenburg',
      jahr: 1989,
      venue: 'Galerie Alte Wäscherei',
      titel: 'Figur',
      untertitel: 'Künstlerkreis Ortenau',
      typ: 'Ausstellungsbeteiligung',
      von: null,
      bis: null,
      kommentar: '',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 58,
      slug: '58',
      ort: 'Tuttlingen',
      jahr: 1989,
      venue: 'Städtische Galerie',
      titel: 'BBK Südbaden',
      untertitel: '',
      typ: 'Ausstellungsbeteiligung',
      von: null,
      bis: null,
      kommentar: '',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 57,
      slug: '57',
      ort: 'Karlsruhe',
      jahr: 1989,
      venue: 'Landesgewerbeamt Baden-Württemberg',
      titel: 'World Games',
      untertitel: '',
      typ: 'Ausstellungsbeteiligung',
      von: null,
      bis: null,
      kommentar: '',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 56,
      slug: '56',
      ort: 'Karslruhe',
      jahr: 1989,
      venue: 'Tempel',
      titel: '1789-1989',
      untertitel: '200 Jahre Französische Revolution',
      typ: 'Ausstellungsbeteiligung mit Katalog',
      von: null,
      bis: null,
      kommentar: '',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 55,
      slug: '55',
      ort: 'Haslach i.K.',
      jahr: 1989,
      venue: 'Kapuzinerkloster',
      titel: 'Drei Länder - Malerei',
      untertitel: '',
      typ: 'Ausstellungsbeteiligung',
      von: null,
      bis: null,
      kommentar: '',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 53,
      slug: '53',
      ort: 'Freiburg i. Brsg.',
      jahr: 1988,
      venue: 'Schwarzes Kloster',
      titel: 'Malerei ???',
      untertitel: '',
      typ: 'Ausstellungsbeteiligung',
      von: null,
      bis: null,
      kommentar: '',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 52,
      slug: '52',
      ort: 'Frankfurt am Main',
      jahr: 1988,
      venue: 'Volksbank',
      titel: 'Der Fuchs',
      untertitel: '',
      typ: 'Ausstellungsbeteiligung mit Katalog',
      von: null,
      bis: null,
      kommentar: '',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 54,
      slug: '54',
      ort: 'Offenburg \u0026 Lons-le-Saunier',
      jahr: 1988,
      venue: 'Galerie „Alte Wäscherei“',
      titel: 'Stadt – Landschaft',
      untertitel: '',
      typ: 'Ausstellungsbeteiligung mit Katalog',
      von: null,
      bis: null,
      kommentar: '',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 51,
      slug: '51',
      ort: 'Rimsingen',
      jahr: 1988,
      venue: 'Galerie Schloß Rimsingen',
      titel: 'Landschaft',
      untertitel: '',
      typ: 'Ausstellungsbeteiligung',
      von: null,
      bis: null,
      kommentar: '',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 129,
      slug: '1987-bausparkasse',
      ort: '???',
      jahr: 1987,
      venue: '???',
      titel: 'Ausstellung Bausparkasse',
      untertitel: '',
      typ: 'Ausstellungsbeteiligung mit Katalog',
      von: null,
      bis: null,
      kommentar: '',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 48,
      slug: '48',
      ort: 'Lahr',
      jahr: 1986,
      venue: 'Altes Rathaus',
      titel: '5 x Malerei',
      untertitel: '',
      typ: 'Ausstellungsbeteiligung',
      von: null,
      bis: null,
      kommentar: '',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 50,
      slug: '50',
      ort: 'Offenburg',
      jahr: 1986,
      venue: 'Galerie Alte Wäscherei',
      titel: 'Liebeszeichen',
      untertitel: 'Künstlerkreis Ortenau',
      typ: 'Ausstellungsbeteiligung mit Katalog',
      von: null,
      bis: null,
      kommentar: '',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 49,
      slug: '49',
      ort: 'Karlsruhe',
      jahr: 1986,
      venue: 'Sparkasse',
      titel: 'Suche nach eigener Identität',
      untertitel: '',
      typ: 'Ausstellungsbeteiligung',
      von: null,
      bis: null,
      kommentar: '',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 46,
      slug: '46',
      ort: 'Karlsruhe',
      jahr: 1985,
      venue: 'Sparkasse',
      titel: 'Bildwelt der Figur',
      untertitel: '',
      typ: 'Ausstellungsbeteiligung',
      von: null,
      bis: null,
      kommentar: '',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 47,
      slug: '47',
      ort: 'Offenburg',
      jahr: 1985,
      venue: 'Galerie Alte Wäscherei',
      titel: 'Wasserzeichen',
      untertitel: 'Künstlerkreis Ortenau',
      typ: 'Ausstellungsbeteiligung mit Katalog',
      von: null,
      bis: null,
      kommentar: '',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
    {
      id: 45,
      slug: '45',
      ort: 'Gengenbach',
      jahr: 1983,
      venue: 'Städtisches Museum Haus Löwenberg',
      titel: 'Vier Künstler aus der Ortenau',
      untertitel: '',
      typ: 'Ausstellungsbeteiligung',
      von: null,
      bis: null,
      kommentar: '',
      bilder: null,
      fotos: null,
      dokumente: null,
    },
  ]

  console.log('ausstellungen', ausstellungen.value, beteiligungen.value)
  const nachJahren = computed(() => {
    const byyears = {}
    ausstellungen.forEach(a => {
      if (a.typ === 'Einzelausstellung' || a.typ === 'Einzelausstellung mit Katalog') {
        if (a.typ === 'Einzelausstellung mit Katalog') {
          a.katalog = true
        }
        if (!byyears[a.jahr]) byyears[a.jahr] = []
        byyears[a.jahr].push(a)
        byyears[a.jahr].sort((i, j) => (i.id < j.id ? -1 : i.id === j.id ? 0 : 1))
      }
    })

    // [[year, exhibitions] ... ]
    return Object.entries(byyears)
      .map(k => [k[0], k[1]])
      .sort((i, j) => (i[0] < j[0] ? 1 : i[0] === j[0] ? 0 : -1))
  })
  const betNachJahren = computed(() => {
    const byyears = {}
    beteiligungen.forEach(a => {
      // if (a.typ === 'Einzelausstellung' || a.typ === 'Einzelausstellung mit Katalog') {
      if (a.typ === 'Einzelausstellung mit Katalog') {
        a.katalog = true
      }
      if (!byyears[a.jahr]) byyears[a.jahr] = []
      byyears[a.jahr].push(a)
      byyears[a.jahr].sort((i, j) => (i.id < j.id ? -1 : i.id === j.id ? 0 : 1))
      // }
    })

    // [[year, exhibitions] ... ]
    return Object.entries(byyears)
      .map(k => [k[0], k[1]])
      .sort((i, j) => (i[0] < j[0] ? 1 : i[0] === j[0] ? 0 : -1))
  })
  console.log('ausstellungen:', nachJahren)
</script>
